name: Test, Build, Push & Deploy Backend

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - backend-deploy-advanced
    paths:
      - 'speedscore-application/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/application-deploy.yml'

env:
  PORT: 4000
  NODE_ENV: production
  API_DEPLOYMENT_URL: https://api.medus.click
  CLIENT_DEPLOYMENT_URL: https://speedscore.medus.click
  COOKIE_DOMAIN: .medus.click
  ACCESS_TOKEN_DURATION: 1d
  REFRESH_TOKEN_DURATION: 7d
  SENDGRID_FROM_ADDRESS: cs14394go@gmail.com
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  MFA_ENCRYPTION_KEY: ${{ secrets.MFA_ENCRYPTION_KEY }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
  GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
  certificateArn: ${{ secrets.CERTIFICATE_ARN_ADV }}
  github_actions_role_arn: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
  github_token: ${{ secrets.TOKEN }}
  github_username: meduscode
  domain: medus.click
  sub_domain: api
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  test:
    name: Run backend tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      API_DEPLOYMENT_URL: http://localhost:4000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run auth tests
        run: |
          npm test -- src/tests/authRoutes/registerUser.test.js
          npm test -- src/tests/authRoutes/loginLogout.test.js

  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: test
    outputs:
      imageTag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate image tag
        id: tag
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        run: echo "$github_token" | docker login ghcr.io -u "$github_username" --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/$github_username/speedscore-api:${{ steps.tag.outputs.tag }} .

      - name: Push Docker image
        run: docker push ghcr.io/$github_username/speedscore-api:${{ steps.tag.outputs.tag }}

  deploy:
    name: Deploy backend to EKS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.github_actions_role_arn }}
          aws-region: us-west-2

      - name: Install Pulumi dependencies
        working-directory: ./speedscore-application
        run: npm ci

      - name: Configure Pulumi stack
        working-directory: ./speedscore-application
        run: |
          pulumi stack select dev
          pulumi config set aws:region us-west-2
          
          pulumi config set speedscore-application-advanced:imageTag ${{ needs.build.outputs.imageTag }}
          pulumi config set speedscore-application-advanced:subDomain $sub_domain
          pulumi config set speedscore-application-advanced:domain $domain
          pulumi config set --secret speedscore-application-advanced:certificateArn "$certificateArn"
          pulumi config set --secret speedscore-application-advanced:githubToken "$github_token"
          pulumi config set --secret speedscore-application-advanced:githubUsername $github_username
          
          
          pulumi config set speedscore-application-advanced:nodeEnv $NODE_ENV
          pulumi config set speedscore-application-advanced:port $PORT
          pulumi config set speedscore-application-advanced:cookieDomain $COOKIE_DOMAIN
          pulumi config set speedscore-application-advanced:clientDeploymentUrl $CLIENT_DEPLOYMENT_URL
          pulumi config set speedscore-application-advanced:apiDeploymentUrl $API_DEPLOYMENT_URL
          pulumi config set speedscore-application-advanced:accessTokenDuration $ACCESS_TOKEN_DURATION
          pulumi config set speedscore-application-advanced:refreshTokenDuration $REFRESH_TOKEN_DURATION
          pulumi config set speedscore-application-advanced:sendgridFromAddress $SENDGRID_FROM_ADDRESS
          pulumi config set --secret speedscore-application-advanced:jwtSecret "$JWT_SECRET"
          pulumi config set --secret speedscore-application-advanced:mongodbUri "$MONGODB_URI"
          pulumi config set --secret speedscore-application-advanced:sessionSecret "$SESSION_SECRET"
          pulumi config set --secret speedscore-application-advanced:mfaEncryptionKey "$MFA_ENCRYPTION_KEY"
          pulumi config set --secret speedscore-application-advanced:sendgridApiKey "$SENDGRID_API_KEY"
          pulumi config set --secret speedscore-application-advanced:ghClientId "$GH_CLIENT_ID"
          pulumi config set --secret speedscore-application-advanced:ghClientSecret "$GH_CLIENT_SECRET"

      - name: Deploy app to EKS
        uses: pulumi/actions@v4
        with:
          work-dir: ./speedscore-application
          command: up
          stack-name: MedusCode-org/speedscore-application-advanced/dev
        env:
          PULUMI_SUPPRESS_OUTPUTS: "true"
