name: Frontend Deploy

on:
  push:
    branches:
      - frontend-deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Docker image
        run: docker build -t ghcr.io/meduscode/speedscore-frontend:latest .

      - name: Login to GHCR
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u meduscode --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/meduscode/speedscore-frontend:latest

      - name: Decode SSL cert
        run: |
          echo "${{ secrets.CERT_PEM_B64 }}" | base64 -d > cert.pem
          echo "${{ secrets.KEY_PEM_B64 }}" | base64 -d > key.pem

      - name: Move certs into ansible folder
        run: |
          mkdir -p ansible/ssl
          mv cert.pem ansible/ssl/cert.pem
          mv key.pem ansible/ssl/key.pem

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/frontend-deploy.yml
          inventory: "54.202.141.107"
          options: |
            --private-key ~/.ssh/id_rsa
            -u ubuntu
